org: eliezer
app: aws-node-express-api-project
service: aws-node-express-api-project
frameworkVersion: "3"

provider:
  name: aws
  runtime: nodejs14.x
  region: sa-east-1
  memorySize: 256

functions:
  api:
    handler: handler.handler
    events:
      - httpApi: "*"
